# Generated by Django 3.1.3 on 2020-11-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='ConversionResult',
        ),
    ]
