# Generated by Django 3.1.3 on 2020-11-21 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20201121_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionresult',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
